# Generated by Django 6.0.1 on 2026-01-20 06:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("custom_orders", "0002_alter_customorderrequest_quoted_price"),
    ]

    operations = [
        migrations.AddField(
            model_name="customorderrequest",
            name="completion_images",
            field=models.JSONField(
                blank=True,
                default=list,
                help_text="Photos of the finished piece for shipped notification",
            ),
        ),
    ]
