# Generated by Django 4.2.7 on 2026-01-05 00:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('orders', '0003_alter_orderitem_product'),
    ]

    operations = [
        migrations.AddField(
            model_name='orderitem',
            name='lighter_type',
            field=models.CharField(default='classic', help_text='Lighter type at time of purchase (snapshot)', max_length=10),
            preserve_default=False,
        ),
    ]
