# Generated by Django 6.0.1 on 2026-01-18 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("orders", "0008_order_is_custom_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="order",
            name="product_image",
            field=models.ImageField(
                blank=True,
                help_text="Photo of the product (optional)",
                null=True,
                upload_to="orders/shipped/",
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipped_at",
            field=models.DateTimeField(
                blank=True, help_text="When the order was shipped", null=True
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="shipping_carrier",
            field=models.CharField(
                default="USPS",
                help_text="Shipping carrier (USPS, UPS, FedEx, etc.)",
                max_length=50,
            ),
        ),
        migrations.AddField(
            model_name="order",
            name="tracking_number",
            field=models.CharField(
                blank=True,
                help_text="Tracking number for shipment",
                max_length=255,
                null=True,
            ),
        ),
        migrations.AlterField(
            model_name="order",
            name="status",
            field=models.CharField(
                choices=[
                    ("pending", "Pending"),
                    ("paid", "Paid"),
                    ("shipped", "Shipped"),
                    ("failed", "Failed"),
                ],
                default="pending",
                max_length=20,
            ),
        ),
    ]
