# Generated by Django 4.2.7 on 2026-01-04 23:49

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0002_refactor_product_images'),
        ('products', '0006_alter_product_currency'),
    ]

    operations = [
    ]
