# Generated by Django 4.2.7 on 2026-01-05 00:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('products', '0007_merge_20260104_2349'),
    ]

    operations = [
        migrations.AddField(
            model_name='product',
            name='lighter_type',
            field=models.CharField(choices=[('classic', 'Classic Bic'), ('mini', 'Mini Bic')], default='classic', max_length=10),
        ),
    ]
