# Generated by Django 6.0.1 on 2026-01-20 05:59

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("products", "0014_remove_product_pattern"),
    ]

    operations = [
        migrations.DeleteModel(
            name="ProductImage",
        ),
    ]
